-- This migration was manually resolved and marked as applied
-- The RealisationImage table was already created in production
-- This migration record was missing locally but existed in the production database
