-- Drop all tables
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;
DROP TABLE IF EXISTS "RealisationImage" CASCADE;
DROP TABLE IF EXISTS "SiteImage" CASCADE;
DROP TABLE IF EXISTS "admin" CASCADE;
DROP TABLE IF EXISTS "_CategoryToRealisations" CASCADE;
DROP TABLE IF EXISTS "_RealisationsToTag" CASCADE;
DROP TABLE IF EXISTS "Realisations" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;
DROP TABLE IF EXISTS "_CategoryToRealisation" CASCADE;
